// Compiles lingo.yaml into lib/lingo.data.ts.
//
// Client components render flavored strings, so the dictionary must be in the bundle, not read
// from disk. The generated file is committed so a fresh checkout, CI and Docker typecheck
// before anything regenerates.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(root, "lingo.yaml");
const target = join(root, "lib", "lingo.data.ts");

function fail(message: string): never {
  console.error(`lingo.yaml: ${message}`);
  process.exit(1);
}

const parsed: unknown = parse(readFileSync(source, "utf8"));
if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
  fail("expected a map of lingo key to its strings");
}

const lingos = parsed as Record<string, unknown>;
const keys = Object.keys(lingos);
if (!keys.includes("english")) fail('must define "english" — it is the default and the reference');

for (const [key, value] of Object.entries(lingos)) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    fail(`"${key}" must be a map of field to string`);
  }
  for (const [field, text] of Object.entries(value as Record<string, unknown>)) {
    if (typeof text !== "string") fail(`"${key}.${field}" must be a string, got ${typeof text}`);
  }
}

// Every other lingo must define exactly english's fields, so a typo fails here rather than
// rendering "undefined".
const reference = Object.keys(lingos.english as Record<string, string>);
for (const key of keys) {
  if (key === "english") continue;
  const fields = Object.keys(lingos[key] as Record<string, string>);
  const missing = reference.filter((f) => !fields.includes(f));
  const extra = fields.filter((f) => !reference.includes(f));
  if (missing.length) fail(`"${key}" is missing: ${missing.join(", ")}`);
  if (extra.length) fail(`"${key}" has fields english doesn't: ${extra.join(", ")}`);
}

const body = keys
  .map((key) => {
    const fields = Object.entries(lingos[key] as Record<string, string>)
      .map(([field, text]) => `    ${field}: ${JSON.stringify(text)},`)
      .join("\n");
    return `  ${key}: {\n${fields}\n  },`;
  })
  .join("\n");

const out = `// GENERATED by \`pnpm lingo:gen\` from lingo.yaml — do not edit by hand.
// Edit lingo.yaml and regenerate; \`pnpm dev\` and \`pnpm build\` do it for you.

import type { RawLingo } from "./lingo.ts";

export const LINGO_KEYS = [
${keys.map((k) => `  "${k}",`).join("\n")}
] as const;

export const RAW_LINGOS = {
${body}
} satisfies Record<string, RawLingo>;
`;

writeFileSync(target, out);
console.log(`lingo: ${keys.length} lingos × ${reference.length} strings → lib/lingo.data.ts`);
